# Generated by Django 4.1.7 on 2023-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name': 'Рецепты', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='content',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='time_updated',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='title',
        ),
        migrations.AddField(
            model_name='recipes',
            name='categoryType',
            field=models.CharField(choices=[('Супы', 'Супы'), ('Закуски', 'Закуски'), ('Салаты', 'Салаты'), ('Дессерты', 'Дессерты'), ('Вторые блюда', 'Вторые блюда')], default=None, max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='name',
            field=models.CharField(default=None, max_length=256, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='recipe',
            field=models.TextField(default=None, verbose_name='Рецепт'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
