# Generated by Django 4.1.7 on 2023-02-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipes_options_remove_recipes_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='categoryType',
            field=models.CharField(choices=[('Супы', 'Супы'), ('Закуски', 'Закуски'), ('Салаты', 'Салаты'), ('Дессерты', 'Дессерты'), ('Вторые блюда', 'Вторые блюда')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe',
            field=models.TextField(verbose_name='Рецепт'),
        ),
    ]
